// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type Password struct {
	ID             uuid.UUID
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	HashedPassword sql.NullString
	Application    sql.NullString
	UserID         uuid.NullUUID
}

type User struct {
	ID             uuid.UUID
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	HashedPassword sql.NullString
	Username       sql.NullString
	IsAdmin        sql.NullBool
}
